/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gt.etl.ia.gui;

import com.gt.etl.ia.database.ManejadorDB;
import com.gt.etl.ia.manejadores.AgregarDatosTabla;
import com.gt.etl.ia.manejadores.Archivo;
import com.gt.etl.ia.manejadores.EjecutarCodigo;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bryan
 */
public class Principal extends javax.swing.JFrame {
    
    private final Archivo manejadorArchivo;
    private final EjecutarCodigo ejecutarCodigo;
    private final ManejadorDB manejadorDB;
    private final AgregarDatosTabla agregarDatosTabla;
    private String pathArchivoCSV;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        deshabilitarComponentes(false);
        this.manejadorArchivo = Archivo.getInstancia();
        this.ejecutarCodigo = EjecutarCodigo.getInstancia();
        this.manejadorDB = ManejadorDB.getInstacia();
        this.agregarDatosTabla = AgregarDatosTabla.getAgregarDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelConPestanias = new javax.swing.JTabbedPane();
        panelErrores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneErrores = new javax.swing.JTextPane();
        lblErrores = new javax.swing.JLabel();
        panelEmpleados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        panelTrabajo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTrabajo = new javax.swing.JTable();
        panelEmpresas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEmpresas = new javax.swing.JTable();
        menu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btnCargar = new javax.swing.JMenu();
        btnLimpiar = new javax.swing.JMenu();
        btnTransformar = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();
        path = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textPaneErrores.setEditable(false);
        jScrollPane1.setViewportView(textPaneErrores);

        lblErrores.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblErrores.setText("Reporte");

        javax.swing.GroupLayout panelErroresLayout = new javax.swing.GroupLayout(panelErrores);
        panelErrores.setLayout(panelErroresLayout);
        panelErroresLayout.setHorizontalGroup(
            panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelErroresLayout.createSequentialGroup()
                        .addComponent(lblErrores)
                        .addGap(0, 801, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelErroresLayout.setVerticalGroup(
            panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErrores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConPestanias.addTab("Errores", panelErrores);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaEmpleados);

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConPestanias.addTab("Empleados", panelEmpleados);

        tablaTrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaTrabajo);

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConPestanias.addTab("Trabajo", panelTrabajo);

        tablaEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaEmpresas);

        javax.swing.GroupLayout panelEmpresasLayout = new javax.swing.GroupLayout(panelEmpresas);
        panelEmpresas.setLayout(panelEmpresasLayout);
        panelEmpresasLayout.setHorizontalGroup(
            panelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEmpresasLayout.setVerticalGroup(
            panelEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConPestanias.addTab("Empresas", panelEmpresas);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConPestanias)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConPestanias)
        );

        menuFile.setText("Archivo");

        btnCargar.setText("Cargar");
        btnCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarMouseClicked(evt);
            }
        });
        menuFile.add(btnCargar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        menuFile.add(btnLimpiar);

        menu.add(menuFile);

        btnTransformar.setText("Transformar");
        btnTransformar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransformarMouseClicked(evt);
            }
        });
        menu.add(btnTransformar);

        menuAcercaDe.setText("Acerca de...");
        menu.add(menuAcercaDe);

        path.setText("Archivo: ");
        menu.add(path);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMouseClicked
        try {
            // TODO add your handling code here:
            cargarArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCargarMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
         deshabilitarComponentes(false);
         this.path.setText("Archivo: ");
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnTransformarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransformarMouseClicked
        // TODO add your handling code here:
        try {
            File file  = new File("ejecutar.sh");
            if (!file.exists()) {
                JOptionPane.showMessageDialog(this, "Error no se encuentra el script de transformacion", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Transformando los datos", "Transformando", JOptionPane.INFORMATION_MESSAGE);
                System.out.println(pathArchivoCSV);
                String command = "sh ejecutar.sh \'" + pathArchivoCSV + "\'";
                System.out.println(command);
                String[] commands = new String[3];
                commands[0] = "sh";
                commands[1] = "ejecutar.sh";
                commands[2] = pathArchivoCSV;
                String salida = EjecutarCodigo.runCommand(commands);
                agregarAlReporte(salida);
                deshabilitarComponentes(true);
                agregarDatosTabla.agregarDatosTablaEmpleados(tablaEmpleados, manejadorDB.listaPersonas());
                agregarDatosTabla.agreagaDatosTablaTrabajo(tablaTrabajo, manejadorDB.listaTrabajos());
                agregarDatosTabla.agregarDatosTablaEmpresa(tablaEmpresas, manejadorDB.listaEmpresas());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTransformarMouseClicked

    private void deshabilitarComponentes(boolean estado) {
        this.panelConPestanias.setVisible(estado);
        this.btnTransformar.setEnabled(estado);
    }
    
    private void cargarArchivo() throws IOException {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Valores separados por comas (.csv)", "csv"));
        int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            pathArchivoCSV = archivo.getAbsolutePath();
            System.out.println(archivo.getAbsolutePath());
            this.path.setText("Archivo: " + archivo.getName());
            JOptionPane.showMessageDialog(this, "Se cargo con exito el archivo.", "Cargado", JOptionPane.INFORMATION_MESSAGE);
            this.btnTransformar.setEnabled(true);
        }
    }
    
    private void agregarAlReporte(String cadena){
        this.textPaneErrores.setText(this.textPaneErrores.getText() + "-------------------------------------------------------------------------------------------------------------------------------\n");
        this.textPaneErrores.setText(this.textPaneErrores.getText() + cadena);
        this.textPaneErrores.setText(this.textPaneErrores.getText() + "\n-------------------------------------------------------------------------------------------------------------------------------\n");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnCargar;
    private javax.swing.JMenu btnLimpiar;
    private javax.swing.JMenu btnTransformar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblErrores;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuFile;
    private javax.swing.JTabbedPane panelConPestanias;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelEmpresas;
    private javax.swing.JPanel panelErrores;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JMenu path;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaEmpresas;
    private javax.swing.JTable tablaTrabajo;
    private javax.swing.JTextPane textPaneErrores;
    // End of variables declaration//GEN-END:variables
}
